version: "3.8"

services:
  mongo1:
    image: mongo:7.0
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "27017" ]
    ports:
      - 27017:27017

    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data/mongo1:/data/db
      - ./data/mongo1:/data/configdb
      - "./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js" # Mount init script
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo1:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=guest
      - MINIO_ROOT_PASSWORD=password
    ports:
      - 9000:9000 # API port
      - 9001:9001 # Console port
    volumes:
      - ./data/minio:/data

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=guest
      - POSTGRES_USER=guest
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    command: postgres -c 'wal_level=replica' -c 'max_wal_senders=10' -c 'max_replication_slots=10'
